# Generated by Django 4.2.4 on 2023-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.TextField(default=False),
        ),
    ]
