# Generated by Django 4.2.4 on 2023-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api_app", "0002_customuser_age_customuser_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="receive_mails",
            field=models.BooleanField(default=True),
        ),
    ]
