# Generated by Django 4.2.4 on 2023-09-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_django", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleaka",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="titleaka",
            name="titleId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="imdb_django.title"
            ),
        ),
    ]
