# Generated by Django 4.2.4 on 2023-09-10 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imdb_django", "0002_alter_titleaka_title_alter_titleaka_titleid"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoriteTVShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tv_show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imdb_django.title",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
