# Generated by Django 4.2.4 on 2023-09-28 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_django", "0003_userfavoritetvshow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="name",
            old_name="nconst",
            new_name="n_const",
        ),
        migrations.RenameField(
            model_name="title",
            old_name="tconst",
            new_name="t_const",
        ),
        migrations.RenameField(
            model_name="titleepisode",
            old_name="parentTconst",
            new_name="parentT_const",
        ),
        migrations.RenameField(
            model_name="titleepisode",
            old_name="tconst",
            new_name="t_const",
        ),
        migrations.RenameField(
            model_name="titleprincipal",
            old_name="nconst",
            new_name="n_const",
        ),
        migrations.RenameField(
            model_name="titlerating",
            old_name="tconst",
            new_name="t_const",
        ),
    ]
