# Generated by Django 4.2.4 on 2023-09-28 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_django", "0004_rename_nconst_name_n_const_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="name",
            old_name="n_const",
            new_name="nconst",
        ),
        migrations.RenameField(
            model_name="title",
            old_name="t_const",
            new_name="tconst",
        ),
        migrations.RenameField(
            model_name="titleepisode",
            old_name="parentT_const",
            new_name="parentTconst",
        ),
        migrations.RenameField(
            model_name="titleepisode",
            old_name="t_const",
            new_name="tconst",
        ),
        migrations.RenameField(
            model_name="titleprincipal",
            old_name="n_const",
            new_name="nconst",
        ),
        migrations.RenameField(
            model_name="titlerating",
            old_name="t_const",
            new_name="tconst",
        ),
    ]
