# Generated by Django 4.2.4 on 2023-10-03 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imdb_django", "0005_rename_n_const_name_nconst_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfavoritetvshow",
            old_name="tv_show",
            new_name="favTitles",
        ),
        migrations.CreateModel(
            name="WishlistShows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wishlistTitles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imdb_django.title",
                    ),
                ),
            ],
        ),
    ]
