# Generated by Django 4.2.4 on 2023-10-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_django", "0006_rename_tv_show_userfavoritetvshow_favtitles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titlerating",
            name="tconst",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="rating",
                serialize=False,
                to="imdb_django.title",
            ),
        ),
    ]
