# Generated by Django 4.2.4 on 2023-10-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_django", "0007_alter_titlerating_tconst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleprincipal",
            name="titleId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prinicpals",
                to="imdb_django.title",
            ),
        ),
    ]
