# Generated by Django 4.2.4 on 2023-10-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_django", "0011_rename_birthyear_name_birth_year_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="titleepisode",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="titleepisode",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="titleepisode",
            name="t_const",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="imdb_django.title",
            ),
        ),
        migrations.AlterField(
            model_name="titleepisode",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season",
                to="imdb_django.title",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="titleepisode",
            unique_together={("t_const", "season_Number", "episode_Number")},
        ),
    ]
