# Generated by Django 4.2.4 on 2023-10-25 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "imdb_django",
            "0012_alter_titleepisode_unique_together_titleepisode_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="name",
            old_name="birth_Year",
            new_name="birthYear",
        ),
    ]
