# Generated by Django 4.2.4 on 2023-10-25 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_django", "0013_rename_birth_year_name_birthyear"),
    ]

    operations = [
        migrations.RenameField(
            model_name="name",
            old_name="birthYear",
            new_name="birth_Year",
        ),
    ]
